### PR TITLE
Ref/regex parse

### PR DESCRIPTION
**Pull request by huseyincansoylu**
## ldn refactoring

- refactored parser functions
- refactored test functions / added new test
- refactored and added sample files for testing
- refactored large-issue-parser js 
- refactored module import/export
- refactored folder structure 
- added uuid (parser and also test for it)

### CODE REVIEW

**Comment by huseyincansoylu** [comment]
when shipping this , we should be sure that we adjust the ldn => https://github.com/keyko-io/filecoin-large-clients-onboarding-bot/issues/127

**Comment by huseyincansoylu** [comment]
discussion : Datacap Request Trigger comment

example link : https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1476#issuecomment-1360221436

here when you click the link you will see the template Simon's use , he uses "*" (star symbol) which is different than in the verifiers tools repo samples because we use "#" instead "*". 

! before shipping this we should fix this problem. 

if it should be "*" , then i need to change the logic and regex inside function.

**Comment by fabriziogianni7** [comment]
@huseyincansoylu we should say Simon to use the version with "#"
after the doc with all the comment template is done, we can reference it to them

**Comment by huseyincansoylu** [comment]
> @huseyincansoylu we should say Simon to use the version with "#" after the doc with all the comment template is done, we can reference it to them

okay i sent message in the slack channel.

**Comment by huseyincansoylu** [comment]
when we ship regex-ref then afterwards we should merge this  => https://github.com/keyko-io/filecoin-large-clients-onboarding-bot/pull/133

**Review by fabriziogianni7 — APPROVED** [review]

**Pull request merged**
